### ISSUE TITLE
Don't modify CSS grids by default to avoid breaking them

### ISSUE THREAD

**Issue by DandyClubs** [sixcious/infy-scroll#96]
### Description

use stylus

````css
#wrapper {
    max-width: 1600px;
    position: relative;
}

#content {
    width: 80%;
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-column-gap: 5px;
    grid-row-gap: 5px;
}


#sidebar-border {
	position: absolute;
	left: 82%;
    top: 5px;
}

div#content div.post {
    overflow-y: hidden;
    overflow-x: hidden;
    max-height: 500px;
}

.autopagerize_page_separator,
.autopagerize_page_info,
div.wp-pagenavi,
div.post.sticky,
div.category-max,
.post:not(.hentry),
.page-title{
    grid-column: 1/-1
}
````

infy scroll is append css 

grid-template-columns: 316.25px 316.25px 316.25px !important;

size is random px per site

so  ignored grid-template-columns: repeat(4, 1fr);

i try ignore grid-template-columns: 316.25px 316.25px 316.25px !important;
````css
요소 {
	/* grid-template-columns: 316.25px 316.25px 316.25px !important; */
}
````

all post grid broekn.

### URL

[Redacted]

### Version

8

### Browser

firefox  edge

### OS

windows 11

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))
